logging:
    level:
      com.author.commons: DEBUG
    config: classpath:log4j2.xml

server:
    port: 8888
#Spring Config
spring:
    application:
      name: author
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        reader:
          db-type: mysql
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.19.163.13:3306/oasystem?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&autoReconnect=true&allowMultiQueries=true
          username: oasystem
          password: izpPnN2LRscYN8j3
          # 下面为连接池的补充设置，应用到上面所有数据源中
          # 初始化连接数大小，最小，最大
          initial-size: 5
          min-idle: 5
          max-active: 20
          # 配置获取连接等待超时的时间
          max-wait: 30000
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          time-between-eviction-runs-millis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          min-evictable-idle-time-millis: 300000
          # 验证数据库连接的有效性
          validation-query: SELECT 1 FROM DUAL
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          # 打开PSCache，并且指定每个连接上PSCache的大小
          pool-prepared-statements: true
          max-open-prepared-statements: 30
          max-pool-prepared-statement-per-connection-size: 30
          use-global-data-source-stat: true
          filters: stat,wall,slf4j
          filter:
            stat:
              merge-sql: true
              slow-sql-millis: 30000
        writer:
          db-type: mysql
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://101.133.137.101:3306/oasystem?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&autoReconnect=true&allowMultiQueries=true
          username: oasystem
          password: izpPnN2LRscYN8j3
          # 下面为连接池的补充设置，应用到上面所有数据源中
          # 初始化连接数大小，最小，最大
          initial-size: 5
          min-idle: 5
          max-active: 20
          # 配置获取连接等待超时的时间
          max-wait: 30000
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          time-between-eviction-runs-millis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          min-evictable-idle-time-millis: 300000
          # 验证数据库连接的有效性
          validation-query: SELECT 1 FROM DUAL
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          # 打开PSCache，并且指定每个连接上PSCache的大小
          pool-prepared-statements: true
          max-open-prepared-statements: 30
          max-pool-prepared-statement-per-connection-size: 30
          use-global-data-source-stat: true
          filters: stat,wall,slf4j
          filter:
            stat:
              merge-sql: true
              slow-sql-millis: 5000
    redis:
      host: 101.133.137.101
      port: 6379
      password: T2rJGEf8DbDAHhNW
      timeout: 30000
      jedis:
        pool:
          max-active: 100
          max-wait: 30000
          max-idle: 50
          min-idle: 0

#Mybati Config
mybatis-plus:  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    call-setters-on-nulls: true
    cache-enabled: true
    map-underscore-to-camel-case: true
  global-config:    db-config:      table-underline: true
  
  
  
  
  
  
  